# Generated by Django 5.1.4 on 2026-05-04 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0002_initial"),
        ("courses", "0001_initial"),
        ("live_sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress_percent", models.FloatField(default=0.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "completed_assignments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="completed_by",
                        to="assignments.assignment",
                    ),
                ),
                (
                    "completed_sessions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="completed_by",
                        to="live_sessions.livesession",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "db_table": "progress",
            },
        ),
    ]
